#!/bin/sh

disk_usage()
{
	printf ": %s root, %s home | " $(rootfull) $(homefull) 
}

battery_left()
{
	emoji=
	if [ $(isbatterycharging) = "Yes" ]
	then
		emoji=
	fi
	printf "$emoji: %s | " $(battery)
}

current_time()
{
	printf ": %s " $(hour)
}

cpu_usage()
{
	emoji=ﰌ
	usage=$(cpuusage)
	if [ bc <<< "$usage > 50" = "1" ]
	then
		emoji=省
	fi
	
	printf "$emoji: %.1f%% | " $usage 
}

ram_usage()
{
	usage=$(bc <<< "$(ramusage) * 100")
	printf "ﴬ: %.2f%% | " $usage
}

while :; do
	xsetroot -name "$(ram_usage && cpu_usage && disk_usage && battery_left && current_time | tr '\n' ' ')"
	sleep 1s
done
